-- Parts:
-- Download typst-preview binary from github, put it in vim.fn.stdpath "data".
-- Launch typst-preview server, and connect to it.
-- Implement all events.
-- Remember to kill the server so there are no process leak.
